//------------------------------------------------------------------------------
// <auto-generated> 
// Copyright © Giga Factory 2023
// This code was generated by a tool. 
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------

class User {
  constructor() {
     this.userId = ""
     this.nickname = ""
     this.isLeave = 0;
     this.lastLoginDt = 0;
     this.createdDt = 0;
}};

class ItemStackable {
  constructor() {
     this.itemId = 0;
     this.count = 0;
}};

class PlayerInfo {
  constructor() {
     this.user_id = '';
     this.ip = '';
     this.nickname = '';
     this.emote_id = 0;
     this.rank = 0;
     this.win = 0;
     this.lose = 0;
     this.result = 0;
}};

class Stage {
  constructor() {
     this.userId = '';
     this.season = '';
     this.score = 0;
     this.win = 0;
     this.lose = 0;
}};

class Mail {
  constructor() {
     this.mail_id = 0;
     this.user_id = '';
     this.mail_type = 0;
     this.subject = '';
     this.text = '';
     this.img_path = '';
     this.reward_list = '';
     this.received_dt = 0;
     this.read_dt = 0;
     this.rewarded_dt = 0;
}};

module.exports = {
  User,
  ItemStackable,
  PlayerInfo,
  Stage,
  Mail,
}
