//------------------------------------------------------------------------------
// <auto-generated> 
// Copyright © Giga Factory 2023
// This code was generated by a tool. 
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------

class AccountLogin {
  constructor(platform_type, platform_id) {
     this.platform_type = platform_type;
     this.platform_id = platform_id;
  }
}

class UserLogin {
}

class FriendPlayInfo {
    constructor(room_key) {
        this.room_key = room_key;
    }
}

class FriendPlayStart {
  constructor(room_name, my_ip) {
    this.room_name = room_name;
    this.my_ip = my_ip;
 }
}

class FriendPlayFinish {
  constructor(room_key, is_win) {
    this.room_key = room_key;
    this.is_win = is_win;
 }
}

class MailList {
}

module.exports = {
  AccountLogin,
  UserLogin,
    FriendPlayInfo,
  FriendPlayStart,
  FriendPlayFinish,
  MailList,
}
