//------------------------------------------------------------------------------
// <auto-generated> 
// Copyright © Giga Factory 2023
// This code was generated by a tool. 
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------

class AccountLogin {
  constructor(platformType, platformId, userId, deviceType, isLeave) {
     this.platformType = platformType;
     this.platformId = platformId;
     this.userId = userId;
     this.deviceType = deviceType;
     this.isLeave = isLeave;
  }
}

class UserLogin {
  constructor(user, itemStackable, stage) {
     this.user = user;
     this.itemStackable = itemStackable;
     this.stage = stage;
  }
}

class RoomInfo {
    constructor(roomKey, player_info_list) {
        this.roomKey = roomKey;
        this.player_info_list = player_info_list;
    }
}

class RandomMatchPlayStart {
    constructor(roomKey, player_info_list) {
        this.roomKey = roomKey;
        this.player_info_list = player_info_list;
    }
}

class RandomMatchPlayFinish {
    constructor(stage, itemStackable, my_rank) {
        this.my_rank = my_rank || -1;
        this.stage = stage || [];
        this.itemStackable = itemStackable || [];
    }
}

class FriendPlayStart {
  constructor(roomKey, playerInfoList) {
    this.roomKey = roomKey;
    this.playerInfoList = playerInfoList;
 }
}

class FriendPlayFinish {
  constructor(stage, itemStackable, myRank) {
    this.myRank = myRank || -1;
    this.stage = stage || [];
    this.itemStackable = itemStackable || [];
 }
}

class ForcePlayOut {}

class MailList {
  constructor(mailList) {
    this.mailList = mailList;
 }
}

module.exports = {
  AccountLogin,
  UserLogin,
    RoomInfo,
    RandomMatchPlayStart,
    RandomMatchPlayFinish,
  FriendPlayStart,
  FriendPlayFinish,
  ForcePlayOut,
  MailList,
}
