//------------------------------------------------------------------------------
// <auto-generated> 
// Copyright © Giga Factory 2023
// This code was generated by a tool. 
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------

class AccountLogin {
  constructor(platformType, platformId, userId, deviceType, isLeave) {
     this.platform_type = platformType;
     this.platform_id = platformId;
     this.user_id = userId;
     this.device_type = deviceType;
     this.is_leave = isLeave;
  }
}

class UserLogin {
  constructor(user, itemStackable, stage) {
     this.user = user;
     this.item_stackable = itemStackable;
     this.stage = stage;
  }
}

class RoomInfo {
    constructor(roomKey, player_info_list) {
        this.room_key = roomKey;
        this.player_info_list = player_info_list;
    }
}

class RandomMatchPlayStart {
    constructor(roomKey, player_info_list) {
        this.room_key = roomKey;
        this.player_info_list = player_info_list;
    }
}

class RandomMatchPlayFinish {
    constructor(stage, itemStackable, my_rank) {
        this.my_rank = my_rank || -1;
        this.stage = stage || [];
        this.item_stackable = itemStackable || [];
    }
}

class FriendPlayStart {
  constructor(roomKey, playerInfoList) {
    this.room_key = roomKey;
    this.player_info_list = playerInfoList;
 }
}

class FriendPlayFinish {
  constructor(stage, itemStackable, myRank) {
    this.my_rank = myRank || -1;
    this.stage = stage || [];
    this.item_stackable = itemStackable || [];
 }
}

class ForcePlayOut {}

class MailList {
  constructor(mailList) {
    this.mail_list = mailList;
 }
}

module.exports = {
  AccountLogin,
  UserLogin,
    RoomInfo,
    RandomMatchPlayStart,
    RandomMatchPlayFinish,
  FriendPlayStart,
  FriendPlayFinish,
  ForcePlayOut,
  MailList,
}
